# Spring Server configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: create 
server:
  port: 8080  